# $OpenBSD: $

COMMENT=	process and decode WWW forms and cookies	

DISTNAME=	Gtk2-WebKit-0.04
CATEGORIES=	www

MAINTAINER=	Abel Camarillo <acamari@the00z.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=	cpan
MAKE_ENV=	TEST_POD=1

#needs 
#p5-ExtUtils-Depends-0.301.tgz
#p5-ExtUtils-PkgConfig-1.07p1.tgz

.include <bsd.port.mk>


