# $OpenBSD: Makefile.template,v 1.60 2010/10/24 20:41:23 ajacoutot Exp $

COMMENT =		perl's URL-safe base64 codec
DISTNAME =		MIME-Base64-URLSafe-0.01
CATEGORIES =		www

MAINTAINER =		Abel Abraham Camarillo Ojeda <acamari@verlet.org>

#Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

.include <bsd.port.mk>
