# $OpenBSD: Makefile,v 1.8 2009/01/14 17:45:04 simon Exp $

COMMENT=        perl interface to the arc4 random number generator

MODULES=	cpan
DISTNAME=	BSD-arc4random-1.43
CATEGORIES=     devel

MAINTAINER=	Abel Abraham Camarillo Ojeda <acamari@the00z.org>

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
